apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io.name: fluxbot
    app.kubernetes.io.component: chat-ops
    app.kubernetes.io.part-of: fluxbot
  namespace: flux
spec:
  selector:
    component: redis
  ports:
  - protocol: TCP
    port: 6379
